### ISSUE TITLE
Minor formatting issues

### ISSUE THREAD

**Issue by vr8hub** [ConcaveTrillion/hilaire-belloc_the-servile_state#1]
Really minor stuff, not worth creating multiple issues.

- [x] The dedication doesn't need <div>s. Even if it needed to be targeted, you can do so with `#dedication p` and `#dedication b`. But, it doesn't need to be targeted; the text doesn't need to be enlarged.
- [x] Balloc's signature in the preface should be regular case (H. Belloc.), and the p should have an `epub:type` of `z3998:signature`. Then add the CSS for that, which will small-cap it.
- [x] For the introduction alpha `ol` CSS, a couple of things: since our id's are unique, just the section id is sufficient for targeting, e.g. #introduction, and…
- [x] … `list-style-type` is inherited from the container, so just `#introduction ol ol` is sufficient for getting the second level list.
- [x] Also, we try to keep our custom CSS separate from the standard CSS, i.e. all the custom CSS at the top, and then the standard CSS grouped by what it's for—dedication, epigraph, etc.
- [x] Chapter 3, the first "villæ" still has the ligature instead of "ae".
- [x] Chapter 7's bridgehead, last section "—to wit, …", the "to" should be capitalized.
- [x] Chapter 8's bridgehead has "… two kinds, The humanist…"; the `the` should be lowercase. Also, the last section "—today the non-owners…", the "today" should be capitalized. (That is a seriously long bridgehead!)
- [x] Footnote 11 is missing a final period.

**Comment by ConcaveTrillion** [comment]
I'll try to have these resolved tonight/tomorrow. Thanks!

**Comment by ConcaveTrillion** [comment]
Changes took faster than I thought. All ready.
